spring.application.name=ideal10spring

spring.datasource.url=${DB_URL:jdbc:h2:mem:ideal10spring;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=${JWT_SECRET:WGRQKde2V+GEfYqu5Bt/jXVg97bOt9mxySNb0PTk8/8=}
jwt.expiration=${JWT_EXPIRATION:86400000}
