spring.application.name=ideal10spring

spring.datasource.url=${DB_URL:jdbc:postgresq://localhost:5432/ideal10spring}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
